// Grading a found record against the pasted reference: the cases the matching bench (tests/browser/match-bench.js)
// showed being held back although right, and the guards that must stay.
var ROOT = require('path').resolve(__dirname, '..');
var A = require(require('path').join(ROOT, 'citations.js'));
var pass = 0, fail = 0;
function rec(o) { return A.normalize({ type: 'journal-article', title: [o.title], author: o.authors || [{ family: o.author || 'Smith', given: 'J.' }], issued: { 'date-parts': [[o.year || 2020]] }, 'container-title': [o.journal || 'Journal'], volume: o.volume, issue: o.issue, page: o.page }); }
function ge(label, text, r, min) { var c = A.matchConfidence(text, r); if (c >= min) pass++; else { fail++; console.log('FAIL ' + label + ': ' + c.toFixed(2) + ' < ' + min); } }
function lt(label, text, r, max) { var c = A.matchConfidence(text, r); if (c < max) pass++; else { fail++; console.log('FAIL ' + label + ': ' + c.toFixed(2) + ' >= ' + max); } }
var GOOD = 0.8, WARN = 0.5;
// a reference that drops the record's subtitle
ge('subtitle dropped', 'König A., Mermin N.D. (1999) Screw rotations and glide mirrors. Proc Natl Acad Sci 96:3502-3506', rec({ title: 'Screw rotations and glide mirrors: Crystallography in Fourier space', author: 'König', year: 1999 }), GOOD);
lt('a two-word main title is not enough on its own', 'Smith J (2020) Deep learning for cats. J 1:1', rec({ title: 'Deep learning: methods and applications', year: 2020 }), WARN);
// British and American spelling, hyphenated compounds written solid
ge('spelling and compounds', 'Anderson AT, Gottfried D (1971) Contrasting behaviour of P, Ti and Nb in a differentiated high-alumina olivine tholeiite and a calcalkaline andesite suite. J Petrol 12:109', rec({ title: 'Contrasting Behavior of P, Ti, and Nb in a Differentiated High-Alumina Olivine Tholeiite and a Calc-Alkaline Andesite Suite', author: 'Anderson', year: 1971 }), GOOD);
ge('sulphide, palaeo, modelling, centre', 'Safina N.P. (2015) Banded sulphide-magnetite ores: palaeo-modelling at the centre. Geol 1:1', rec({ title: 'Banded sulfide–magnetite ores: paleo-modeling at the center', author: 'Safina', year: 2015 }), GOOD);
// ligatures dropped by a PDF ("fi" missing) and a typo in the author
ge('ligature typos', 'Korekina M.A. (2023) Formation conditions and sources of fuids of the frst quartz deposits. Minerals 13:1', rec({ title: 'Formation conditions and sources of fluids of the first quartz deposits', author: 'Korekina', year: 2023 }), GOOD);
ge('author typo', 'Safna N.P., Maslennikov V.V. (2015) Banded sulfide-magnetite ores of Mauk copper massive sulfide deposit. Geol Ore Dep 57:1', rec({ title: 'Banded sulfide-magnetite ores of Mauk copper massive sulfide deposit', author: 'Safina', year: 2015 }), GOOD);
// "(1964a)" is a year even with a page range beside it
ge('year with a letter suffix', 'Chayes F (1964a) A petrographic distinction between Cenozoic volcanics in and around the open oceans. J Geophys Res 69:1573–1588', rec({ title: 'A petrographic distinction between Cenozoic volcanics in and around the open oceans', author: 'Chayes', year: 1964 }), GOOD);
lt('a different year is never green (the page flags the year clash)', 'Chayes F (1975) A petrographic distinction between Cenozoic volcanics in and around the open oceans. J Geophys Res 69:1573', rec({ title: 'A petrographic distinction between Cenozoic volcanics in and around the open oceans', author: 'Chayes', year: 1964 }), GOOD);
// an organisation deposited as the first author: the first person is checked instead
ge('organisation first author', 'Noskevich V.V., Fedorova N.V. (2018) Using the ground penetrating radar method for research of the ancient Vorovskaya Yama copper mine. Geoarchaeology 1:1', rec({ title: 'Using the ground penetrating radar method for research of the ancient “Vorovskaya Yama” copper mine', authors: [{ name: 'Bulashevich Institute of Geophysics of the Ural Branch of RAS' }, { family: 'Noskevich', given: 'V. V.' }], year: 2018 }), GOOD);
// no year in the reference, but title and author are exact
ge('missing year, exact title and author', 'Kasatkin A.V., Kuznetsov A.M. Ore minerals of the Buranovskoe tungsten deposit (Southern Urals). Mineralogy 8(2):5-20', rec({ title: 'Ore minerals of the Buranovskoe tungsten deposit (Southern Urals)', author: 'Kasatkin', year: 2022 }), GOOD);
lt('missing year and wrong author stays amber', 'Ivanov P.Q. Ore minerals of the Buranovskoe tungsten deposit (Southern Urals). Mineralogy 8(2):5-20', rec({ title: 'Ore minerals of the Buranovskoe tungsten deposit (Southern Urals)', author: 'Kasatkin', year: 2022 }), GOOD);
// guards that must stay
lt('different title', 'Smith J (2020) Thermal conductivity of olivine at mantle pressures. J 1:1', rec({ title: 'Nanometre-scale thermometry in a living cell', year: 2020 }), WARN);
lt('a corrigendum is not the paper', 'Kucsko G (2013) Nanometre-scale thermometry in a living cell. Nature 500:54', rec({ title: 'Corrigendum: Nanometre-scale thermometry in a living cell', author: 'Kucsko', year: 2013 }), WARN);
ge('exact reference is 1', 'Kucsko G, Maurer PC (2013) Nanometre-scale thermometry in a living cell. Nature 500:54-58', rec({ title: 'Nanometre-scale thermometry in a living cell', author: 'Kucsko', year: 2013 }), 0.99);
lt('typo tolerance does not merge short different words', 'Smith J (2020) Iron ore in the deep. J 1:1', rec({ title: 'Icon core on the deer', year: 2020 }), WARN);
// scripts other than Latin: the reference and the record may be in Cyrillic, CJK or Greek, or the record transliterated
ge('Cyrillic reference and record', 'Пеков И.В. (1998) Минералы, впервые открытые на территории бывшего Советского Союза. М.: Океан Пикчерз, 369 с.', rec({ title: 'Минералы, впервые открытые на территории бывшего Советского Союза', authors: [{ family: 'Пеков', given: 'И. В.' }], year: 1998 }), GOOD);
lt('Cyrillic reference against a different Cyrillic title', 'Пеков И.В. (1998) Минералы, впервые открытые на территории бывшего Советского Союза. М.: Океан Пикчерз, 369 с.', rec({ title: 'Геохимия щелочных массивов Кольского полуострова', authors: [{ family: 'Пеков', given: 'И. В.' }], year: 1998 }), WARN);
ge('ё and е are the same letter', 'Семёнов А.Б. (2005) Учёт неопределённости в моделях. Геология 3:1-9', rec({ title: 'Учет неопределенности в моделях', authors: [{ family: 'Семенов', given: 'А. Б.' }], year: 2005 }), GOOD);
ge('Cyrillic author against a transliterated record', 'Пароникян Е.Г., Арутюнян А.С. (2020) Синтез новых производных пиридина. ЖОрХ 56:414-421', rec({ title: 'Синтез новых производных пиридина', authors: [{ family: 'Paronikyan', given: 'E. G.' }], year: 2020 }), GOOD);
ge('Japanese reference and record', '山田太郎, 佐藤花子 (2015) 河川堤防の浸透破壊に関する実験的研究, 土木学会論文集B1, 71, 123-130', rec({ title: '河川堤防の浸透破壊に関する実験的研究', authors: [{ family: '山田', given: '太郎' }], year: 2015 }), GOOD);
lt('Japanese reference against a different Japanese title', '山田太郎, 佐藤花子 (2015) 河川堤防の浸透破壊に関する実験的研究, 土木学会論文集B1, 71, 123-130', rec({ title: '鋼橋の疲労き裂の進展挙動に関する解析的検討', authors: [{ family: '山田', given: '太郎' }], year: 2015 }), WARN);
ge('Greek reference and record', 'Παπαδόπουλος Γ. (2010) Η γεωλογία της Κρήτης και οι σεισμοί της. Δελτίο Ελληνικής Γεωλογικής Εταιρείας 43:1-10', rec({ title: 'Η γεωλογία της Κρήτης και οι σεισμοί της', authors: [{ family: 'Παπαδόπουλος', given: 'Γ.' }], year: 2010 }), GOOD);
ge('Latin behaviour unchanged', 'Kucsko G, Maurer PC (2013) Nanometre-scale thermometry in a living cell. Nature 500:54-58', rec({ title: 'Nanometre-scale thermometry in a living cell', author: 'Kucsko', year: 2013 }), 0.99);
// a compact reference with no title: author, year, volume and first page agreeing is a match; three of the four is amber
var babichev = [{ family: 'Бабичев', given: 'А. В.' }, { family: 'Гладышев', given: 'А. Г.' }, { family: 'Дюделев', given: 'В. В.' }, { family: 'Колодезный', given: 'Е. С.' }];
ge('title-less Russian citation with volume and page', 'Бабичев А.В., Гладышев А.Г., Дюделев В.В. и др. // Письма в ЖТФ. 2020. Т. 46. № 9. С. 35', rec({ title: 'Лазеры на квантовых ямах с двойной активной областью', authors: babichev, year: 2020, volume: '46', issue: '9', page: '35-38', journal: 'Письма в журнал технической физики' }), GOOD);
lt('title-less citation with a different page is not green', 'Бабичев А.В., Гладышев А.Г., Дюделев В.В. и др. // Письма в ЖТФ. 2020. Т. 46. № 9. С. 35', rec({ title: 'Лазеры на квантовых ямах', authors: babichev, year: 2020, volume: '46', issue: '9', page: '112-115', journal: 'Письма в журнал технической физики' }), GOOD);
lt('title-less citation with a different first author stays low', 'Иванов П.П., Гладышев А.Г. // Письма в ЖТФ. 2020. Т. 46. № 9. С. 35', rec({ title: 'Лазеры на квантовых ямах', authors: [{ family: 'Бабичев', given: 'А. В.' }], year: 2020, volume: '46', issue: '9', page: '35-38' }), WARN);
ge('title-less physics citation in Latin', 'L.J. Campbell et al., Physica B 211 (1995) 52', rec({ title: 'Magnetic field dependence of the specific heat', authors: [{ family: 'Campbell', given: 'L. J.' }], year: 1995, volume: '211', page: '52-56', journal: 'Physica B' }), GOOD);
ge('same author, year, volume and first page is the same article whatever the title says', 'Campbell LJ (1995) Thermal transport in copper oxides. Physica B 211:52', rec({ title: 'Magnetic field dependence of the specific heat', authors: [{ family: 'Campbell', given: 'L. J.' }], year: 1995, volume: '211', page: '52-56' }), GOOD);
lt('the same volume but another page is not the same article', 'Campbell LJ (1995) Thermal transport in copper oxides. Physica B 211:52', rec({ title: 'Magnetic field dependence of the specific heat', authors: [{ family: 'Campbell', given: 'L. J.' }], year: 1995, volume: '211', page: '140-146' }), WARN);
// the journal's own Crossref record shares its name with every reference to it and is never the match
lt('a journal record is never the match', 'Воронина Л.В. (2023) Когнитивные механизмы персуазивности политического дискурса. Вестник Пермского университета. Российская и зарубежная филология 15(1):17-27', A.normalize({ type: 'journal', title: ['Вестник Пермского университета. Российская и зарубежная филология'], issued: { 'date-parts': [[2009]] } }), WARN);
lt('a journal record is never the match (Latin)', 'Smith J (2020) Deep learning for crystals. Journal of Applied Crystallography 53:1-9', A.normalize({ type: 'journal', title: ['Journal of Applied Crystallography'], issued: { 'date-parts': [[1968]] } }), WARN);
// Crossref holds a translated title with the native-script original beside it; romanised authors do not stop the match
ge('Chinese reference against a record with an English title and a Chinese original-title', '彭 翀, 郭 祖源, 彭 仲仁. 国外社区韧性的理论与实践进展. 国际城市规划, 2017, 32: 60-66.', A.normalize({ type: 'journal-article', title: ['Research Progress on the Theory and Practice of Foreign Community Resilience'], 'original-title': ['国外社区韧性的理论与实践进展'], author: [{ family: 'Peng', given: 'Chong' }, { family: 'Guo', given: 'Zuyuan' }], issued: { 'date-parts': [[2017]] }, volume: '32', page: '60-66' }), GOOD);
ge('Japanese reference against a record with an English title and a Japanese original-title', '8) 立川康人 他6名，超多数アンサンブル気候予測実験データを用いた極値河川流量の将来変化の分析，土木学会論文集 B1（水工学） Vol. 73, No. 3, pp. 77-90, 2017', A.normalize({ type: 'journal-article', title: ['FUTURE CHANGE ANALYSIS OF EXTREME FLOODS USING LARGE ENSEMBLE CLIMATE SIMULATION DATA'], 'original-title': ['超多数アンサンブル気候予測実験データを用いた極値河川流量の将来変化の分析'], author: [{ family: 'Tachikawa', given: 'Yasuto' }], issued: { 'date-parts': [[2017]] }, volume: '73', issue: '3', page: '77-90' }), GOOD);
lt('a different Chinese original-title stays low', '彭 翀, 郭 祖源, 彭 仲仁. 国外社区韧性的理论与实践进展. 国际城市规划, 2017, 32: 60-66.', A.normalize({ type: 'journal-article', title: ['Urban Green Space Planning in Hangzhou'], 'original-title': ['杭州城市绿地系统规划研究'], author: [{ family: 'Wang', given: 'Hui' }], issued: { 'date-parts': [[2017]] }, volume: '32', page: '29-39' }), WARN);
lt('a page range is not a volume and a page', 'Лисицын А.П., Сагалевич A.M. Главные открытия в океане. Наука в России. 2001; (1): 15-25.', rec({ title: 'Laboratory medicine in transition', authors: [{ family: 'Лисицын', given: 'А. П.' }], year: 2001, volume: '25', issue: '1-2', page: '15-20' }), GOOD);
console.log(pass + ' passed, ' + fail + ' failed');
process.exitCode = fail ? 1 : 0;
