var ROOT = require('path').resolve(__dirname, '..');
var FIX = require('path').join(__dirname, 'fixtures');
const A = require(require('path').join(ROOT, 'citations.js'));
const j = (o) => Object.assign({ type: 'journal-article', title: ['A title'], author: [{ family: 'Doe', given: 'Jane' }], issued: { 'date-parts': [[2020]] }, 'container-title': ['Journal of Cats'], volume: '12', issue: '3', page: '45-67', DOI: '10.1/x' }, o);
const show = (label, rec, styles) => { console.log('## ' + label); (styles || ['apa']).forEach(st => console.log('  [' + st + '] ' + A.format(rec, st))); };
show('J.-P. initials', j({ author: [{ family: 'Sartre', given: 'J.-P.' }, { family: 'Lee', given: 'Jean-Pierre' }] }), ['apa', 'harvard', 'ieee', 'carnegie', 'vancouver']);
show('caps names', j({ author: [{ family: 'LEE', given: 'IAN' }, { family: 'SMITH', given: 'JOHN' }, { family: 'Maurer', given: 'PC' }, { family: 'DOE', given: 'J.D.' }] }), ['apa', 'mla', 'chicago']);
show('suffix', j({ author: [{ family: 'King', given: 'Martin Luther', suffix: 'Jr.' }, { family: 'Doe', given: 'Jane' }] }), ['apa', 'mla', 'chicago', 'ieee']);
show('italic ? title book', j({ type: 'book', title: ['Who owns the future?'], 'container-title': undefined, volume: undefined, issue: undefined, page: undefined, publisher: 'Penguin', 'publisher-location': 'London' }), ['apa', 'mla', 'chicago', 'harvard', 'ieee', 'vancouver', 'carnegie']);
show('article-number == page', j({ page: '103208', 'article-number': '103208', volume: '95', issue: undefined }), ['apa', 'ieee']);
show('harvard chapter + apa single page', j({ type: 'book-chapter', 'container-title': ['The Big Book'], editor: [{ family: 'Ed', given: 'Alan' }, { family: 'Ed', given: 'Beth' }, { family: 'Ed', given: 'Carl' }], publisher: 'Springer', 'publisher-location': 'Berlin', page: '5', volume: undefined, issue: undefined }), ['apa', 'harvard', 'mla', 'vancouver', 'ieee', 'chicago']);
show('issue no volume', j({ volume: undefined }), ['harvard', 'apa']);
show('preprint host', j({ type: 'posted-content', 'container-title': undefined, volume: undefined, issue: undefined, page: undefined, publisher: 'openRxiv', institution: [{ name: 'bioRxiv' }] }), ['apa', 'mla', 'chicago', 'harvard', 'vancouver', 'ieee', 'carnegie']);
show('given only', j({ author: [{ given: 'Consortium' }] }), ['apa', 'mla']);
show('edited book no authors', j({ type: 'book', author: undefined, editor: [{ family: 'Ed', given: 'Alan' }], title: ['Handbook of Cats'], 'container-title': undefined, volume: undefined, issue: undefined, page: undefined, publisher: 'Wiley', edition: '3' }), ['apa', 'mla', 'chicago', 'harvard', 'carnegie', 'vancouver', 'ieee']);
show('no source', j({ 'container-title': undefined, volume: undefined, issue: undefined, page: undefined }), ['apa', 'chicago']);
show('springer chapter series', j({ type: 'book-chapter', 'container-title': ['Use R!', 'ggplot2'], volume: undefined, issue: undefined, page: '189-201', publisher: 'Springer', 'publisher-location': 'Cham', DOI: '10.1007/978-3-319-24277-4_9' }), ['apa', 'carnegie', 'bibtex', 'ris']);
show('literal author exports', j({ author: [{ name: 'World Health Organization' }] }), ['bibtex', 'ris', 'endnote', 'apa']);
show('bibtex escapes', j({ title: ['Back\\slash & 100% of #tags_here {braces} ~tilde ^caret'] }), ['bibtex']);
show('thesis/report', j({ type: 'dissertation', title: ['A thesis'], 'container-title': undefined, volume: undefined, issue: undefined, page: undefined, publisher: 'MIT', 'publisher-location': 'Cambridge, Massachusetts', degree: ['M.S.'] }), ['bibtex', 'carnegie', 'apa']);
show('marc punctuation', j({ type: 'book', title: ['On the origin of species /'], author: [{ family: 'Darwin', given: 'Charles' }], 'container-title': undefined, volume: undefined, issue: undefined, page: undefined, publisher: 'John Murray,', 'publisher-location': 'London :', abstract: '<jats:title>Abstract</jats:title><jats:p>Line one.</jats:p><jats:p>Line two.</jats:p>', 'number-of-pages': '502' }), ['vancouver', 'carnegie', 'ris']);
show('vancouver missing year', j({ issued: undefined }), ['vancouver', 'apa', 'harvard']);
show('carnegie series volume', j({ type: 'book-chapter', 'container-title': ['Bulletin of Carnegie Museum of Natural History', 'Fanfare for an Uncommon Paleontologist'], editor: [{ family: 'Dawson', given: 'Mary R.' }, { family: 'Lillegraven', given: 'Jason A.' }], volume: '36', page: '245-266', issue: undefined, publisher: 'Carnegie Museum of Natural History' }), ['carnegie']);
console.log('titleOnly conf:', A.matchConfidence('Deep residual learning for image recognition', j({ title: ['Deep Residual Learning for Image Recognition'], author: [{ family: 'He', given: 'K' }], issued: { 'date-parts': [[2016]] } }), { titleOnly: true }));
